---

AllCops:
  Exclude:
    - bin/**/*
    - vendor/**/*
  TargetRubyVersion: 2.4

### METRICS ###
Metrics/LineLength:
  Max: 80

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - evostream-event.gemspec

Metrics/LineLength:
  Exclude:
    - spec/**/*

### SECURITY ###
Security/YAMLLoad:
  Enabled: false

### STYLES ###
Style/RescueStandardError:
  Enabled: false
