---

AllCops:
  Exclude:
    - bin/**/*
    - vendor/**/*
  TargetRubyVersion: 2.4

Metrics/LineLength:
  Max: 80

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - evostream-event.gemspec

Metrics/LineLength:
  Exclude:
    - spec/**/*

Security/YAMLLoad:
  Enabled: false
