sudo: false

language: ruby

rvm:
  - 2.3.1
  - 2.4

before_install: gem install bundler -v 1.13.6

notifications:
  email: false
  slack:
    on_success: always
    rooms:
      secure: wq9V5QaS9tQPr0gaHtRCuLPbMei+gO6tHNwkDFbNUo9SFb1W/0zdxapnxQhxIcyqYfLanvnjprQHme3OXJnVP59jbG4CIfe0NMcOO4s+DYBJvEBEj2+li263A96mJCdXxVojDEZ83E/0+PppfNut+CBtvWikAkMyvvbPNyd0XkQ7dYK6iWEdLBRjDmC8HYRPZgLAcHADB85F60/BuUwsWkZhCyymAXU1McPVFu8OMBpb7LJhLy9MqB5W6VpOlmUYDeTasl5h+tV7ci2cr8Mcu6EAuSUWMG/bBm57z65cEG7kz750gw1Vt8h+mUgcmWfsXBbsJZrh7xpHOulynMcf0rwVcqanvfb9suHYHf0HXon9+ljlwbP2J91wrQqezmvZqhpekPYXD3Qz8qCtdSzhSOdVzE6LaAtDKrj6p9CJ1hwhp5tWUA1roz8pNdKCOHNkmcrWCOggnhDlxrBkwwVoDvVfIl9yL1kezL87mD8vRrSJWRzKjoE85fjFJM9JR6Ie/Bcf4FjWeWRNwAv4LrLOUBDI8Bs0KNdsw+pK/69EEG5N5gnqGmqs6KOY7Ucs75Hq3ZWop85GFocQnw0k4U6YarDvzrTKz/hcrSTCwnNG8jkpKRQ6x+76rlLPcXwaGkL34AmVJ7SFu8a5u8UJUYigPej6c58rBg5wwcvw++izUKg=
