---

name: Linter

on:
  push:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install gems
      run: |
        gem install --no-document bundler:2.2.16
        gem install
    - name: Rubocop
      run: bundle exec rubocop
    - name: Reek
      run: bundle exec reek
